[package]
name = "grinta_scripts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
sncast_std = "0.57.0"
starknet = "2.14.0"
grinta = { path = "../" }

[lib]
sierra = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
    "grinta::safe_engine::SAFEEngine",
    "grinta::collateral_join::CollateralJoin",
    "grinta::pid_controller::PIDController",
    "grinta::grinta_hook::GrintaHook",
    "grinta::safe_manager::SafeManager",
    "grinta::mock::erc20_mintable::ERC20Mintable",
    "grinta::mock::mock_ekubo_oracle::MockEkuboOracle",
    "grinta::oracle_relayer::OracleRelayer",
]

[scripts]
deploy_sepolia = "sncast --profile sepolia script run deploy_sepolia --package grinta_scripts"
upgrade_sepolia = "sncast --profile sepolia script run upgrade_sepolia --package grinta_scripts"

[tool.fmt]
sort-module-level-items = true
max-line-length = 120
